# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beju < Formula
  desc "A tool to help you manage your brew and cask installs using ansible"
  homepage "https://juli.sh"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.1.3/beju_0.1.3_Darwin_arm64.tar.gz"
      sha256 "99c9f17c6cb015c6a6c6b0dde10686c36a6cff9e4da82f6222fee7f0616611a7"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.1.3/beju_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "8297940680e6be1e754f6ba8b0473a6b06a8a0be0b8b02bf87d02da0bd608437"

      def install
        bin.install "beju"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.1.3/beju_0.1.3_Linux_x86_64.tar.gz"
      sha256 "fc09d8edf8270326198f09f5915b7aacdf58e58bb56ee3bfb6d1f6c1d5112047"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.1.3/beju_0.1.3_Linux_armv6.tar.gz"
      sha256 "1076095e6d52f91d23264c5288d881cfedc55a90249e0525912a3ca86a8ca6e3"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.1.3/beju_0.1.3_Linux_arm64.tar.gz"
      sha256 "6eab86657a112e91b4a7fc2b74851af77f688434ecc16c1e8618e6ef84f8c1d2"

      def install
        bin.install "beju"
      end
    end
  end
end
