# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brew2ansible < Formula
  desc "Tool to helps you manage your brew and cask installs using ansible"
  homepage "https://juli.sh"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v1.0.0/brew2ansible_1.0.0_Darwin_arm64.tar.gz"
      sha256 "23105b25396e5f3c0b2ec48b759b68fe0f5ab34fe50c9d2a1cbc59d986b76bde"

      def install
        bin.install "brew2ansible"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v1.0.0/brew2ansible_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "8eef386d008d0ec1de6bea9a041bb868111fcb60858840fff19ffbbda671b676"

      def install
        bin.install "brew2ansible"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v1.0.0/brew2ansible_1.0.0_Linux_x86_64.tar.gz"
      sha256 "e0beb5ac5375ef79a33d4ab3e4402f1bb4f3d16abd299cfa14652f5e558e1c2e"

      def install
        bin.install "brew2ansible"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v1.0.0/brew2ansible_1.0.0_Linux_armv6.tar.gz"
      sha256 "a3eff8e64acbf588155897ecd7e65a6c0a17dd36b47b2591a5a706b094dd4016"

      def install
        bin.install "brew2ansible"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v1.0.0/brew2ansible_1.0.0_Linux_arm64.tar.gz"
      sha256 "ee8202119a3b1f37c56ee897d4e248e1b2cf7647581864c36d59051de082f861"

      def install
        bin.install "brew2ansible"
      end
    end
  end
end
