# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brew2ansible < Formula
  desc "Tool to helps you manage your brew and cask installs using ansible"
  homepage "https://juli.sh"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.2.1/brew2ansible_0.2.1_Darwin_arm64.tar.gz"
      sha256 "197060bd7d52922ad0529a99f453aa549147f0fd8adb52278d1e06b17105d74b"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.2.1/brew2ansible_0.2.1_Darwin_x86_64.tar.gz"
      sha256 "919b98bf0dd63d71db771596e71a56fed184d7eebb41657729e8d6f8e96de12d"

      def install
        bin.install "beju"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.2.1/brew2ansible_0.2.1_Linux_armv6.tar.gz"
      sha256 "6f4c9d724bfaa2d5a1b347d7fc05a9f79753f78ea29bdf525ede31d7cee46d21"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.2.1/brew2ansible_0.2.1_Linux_arm64.tar.gz"
      sha256 "211564a66cf8f7f9dcacd4de26b11c422c9d4f1422d0bb0c38d164b77e59610c"

      def install
        bin.install "beju"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jufabeck2202/brew-to-mac-ansible-playbook/releases/download/v0.2.1/brew2ansible_0.2.1_Linux_x86_64.tar.gz"
      sha256 "e3ef95c5c60fde5b6e202eaccd9966fb0e1743daa67f74c074a05126c97cd88a"

      def install
        bin.install "beju"
      end
    end
  end
end
